language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
after_script:
  - yarn codecov
notifications:
  email: false
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov